### ISSUE TITLE
query other actor at command handler of EventSourcedActor

### ISSUE THREAD

**Issue by aprooks** [yevhen/Orleankka#54]
I'm having difficulties of implementing following scenorio.

Right before receiving a payment for an item, I want to make a call to (for example ) warehouse service, via exposed API endpoint (I cannot make a reservation, just buy or check if available). The idea is to minimize probability of receiving a money for an item that was already sold. At first, I tried  to create an Actor, that encapsulates actual API call, and returns availability via query. Like this:

```  C#
public class Basket : EventSourcedActor{
   public IEnumerable<Event> Handle(Checkout cmd){
      var warehouse = System.ActorOf<Warehouse>(0);
      var itemAvailable = await warehouse.Ask(new IsAvailable(cmd.ItemId));  //async needed!
      if(!itemAvailable) throw Exception("we don't have this item!");
      //blabla
      yield return new ItemCheckedOut(cmd.ItemId);
   }
}
```
First questions, can we make an async command handler and does it really make sense?

If not, these are couple of workarounds I'm thinking of:
1. make warehouse a simple service with a synchronous call. 
2. add an extra step with a checking actor

```  C#
public class Basket : EventSourcedActor{
   public IEnumerable<Event> Handle(PrepaireForChecking cmd){
      var warehouse = System.ActorOf<Warehouse>(0);
      warehouse.Tell(new EnsureItemsAvailable(){
         ItemId = cmd.ItemId,
         onComplete  = this.Self
      });  //warehouse will send commands back to continue or cancel checking out
      yield return new ItemsArePrepairedForCheckingout();
   });
  
   public IEnumerable<Event> Handle(Checkout cmd){      
      //handle payment
      yield return new ItemPurchased();
   }

   public IEnumerable<Event> Handle(CancelCheckoutDueToItemUnavailability cmd){
      yield return new CheckingoutCancelled();
   }
}
```
The second approach seems to make more sense if such history is needed in domain model, otherwise first 1 

Are there any other ideas? Am I doing something that makes sense with Event Sourcing?

**Comment by yevhen** [comment]
I don't see any problems with having async command hander. It's absolutely valid.

> If not, these are couple of workarounds I'm thinking of:
1. make warehouse a simple service with a synchronous call.
2. add an extra step with a checking actor

1) will block thread - bad
2) you're not awaiting `Tell` operation - bad, will blow in unpredictable ways 

The `EventSourcingActor` is just a sample. You're free to bend it to the needs of you application. That's why I'm releasing it as just an example, not as part of the core. In fact, copy-pasting it into your codebase and poking it until it fits is highly encouraged :smile: 

Regarding async command handler. There is a `DispatchAsync` method that is able to call both sync and async message handlers in a uniform way. You will pay a completely negligible price on wrapping/unwrapping task result for sync handlers but that's just it.

Try this code:

```cs
protected override async Task<object> HandleCommand(Command cmd)
{
    var events = (await DispatchAsync<IEnumerable<Event>>(cmd)).ToArray();

    foreach (var @event in events)
        Dispatch(@event);

    return (object) events;
}
```

**Comment by aprooks** [comment]
Sounds good, thank you
